### ISSUE TITLE
Other languages than PHP

### ISSUE THREAD

**Issue by yhoiseth** [pixelant/platformsh-analytics#3]
Hi,

I read [the introductory blog post](https://platform.sh/blog/2019/faster-friendlier-analytics-for-your-php-project/). This looks like a very useful tool. Thanks a lot for sharing 🙂

I'm curious about using it for projects in other languages than PHP, such as Python. It's not clear to me whether it's possible or, if not, what it would take.

**Comment by mabolek** [comment]
Hi Yngve!

The tool uses the log format in `/var/logs/php.access.log`. If you get Python to output logs in that format, it shouldn't take much work. If the log format is different, you'll have to do quite a rewrite.

**Comment by yhoiseth** [comment]
I see. That log is empty in my (Python) project. Looking at [the documentation](https://docs.platform.sh/development/logs.html), I can't find any equivalent `python.access.log`.

@crell You wouldn't happen to know if there's any way to get an equivalent to `php.access.log` in Python projects?

**Comment by Crell** [comment]
From what I've been told, on non-PHP the access log appears in `app.log` in the same format.  So you *should* be able to adapt the script to look for one file and then fall back to the other.  I'm not 100% certain if other data shows up in `app.log` so you may need some additional error handling around it.

**Comment by royallthefourth** [comment]
`app.log` only shows what your app writes to stdout, so you'll need to instrument the application to generate log entries in your desired format. The easiest thing is usually to wrap everything in a logging middleware. Getting things like per-request memory may not be as straightforward in other languages, or at least I haven't succeeded with Go.

**Comment by yhoiseth** [comment]
Thanks :)
